version: '3.4'

services:
  postgres:
    image: postgres:14.5
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user-03
      POSTGRES_PASSWORD: pwd-03

  pgadmin4:
    image: dpage/pgadmin4:6.12
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user-03@email.com'
      PGADMIN_DEFAULT_PASSWORD: pwd-03

volumes:
  postgres-data: