version: '3.4'

services:
  redis:
    image: redis:7.0.4
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - '8080:8081'
    depends_on:
      - redis
    environment:
      REDIS_HOSTS: local:redis:6379

volumes:
  redis-data: