version: '3.4'

services:
  mongo:
    image: mongo:5.0.11
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: user-07
      MONGO_INITDB_ROOT_PASSWORD: pwd-07
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user-07
      ME_CONFIG_MONGODB_ADMINPASSWORD: pwd-07
      ME_CONFIG_MONGODB_URL: mongodb://user-07:pwd-07@mongo:27017

  rotten-potatoes:
    container_name: rotten-potatoes
    build:
      context: rotten-potatoes
      args:
        - MONGODB_DB=admin
        - MONGODB_HOST=mongo
        - MONGODB_PORT=27017
        - MONGODB_USERNAME=user-07
        - MONGODB_PASSWORD=pwd-07
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - mongo
    environment:
      MONGODB_DB: admin
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      MONGODB_USERNAME: user-07
      MONGODB_PASSWORD: pwd-07

volumes:
  mongodb-data: